version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  dev-db:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - 5455:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    


name: fastapi-tdd