version: "3.4"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
